apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-web
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-web
  replicas: {{ .Values.config.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-web
        app.kubernetes.io/part-of: {{ .Release.Name }}
        helm.sh/chart: {{ include "chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
        - name: {{ .Release.Name }}-web
          image: "{{ .Values.config.image }}:{{ .Values.config.tag }}"
          imagePullPolicy: {{ .Values.config.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: debug
          resources:
  {{ toYaml .Values.resources | indent 12 }}
  {{- if .Values.nodeSelector }}
nodeSelector:
  {{ toYaml .Values.nodeSelector | indent 8 }}
  {{- end }}
