apiVersion: v1
entries:
  keycloak:
  - annotations:
      category: DeveloperTools
    apiVersion: v2
    appVersion: 15.0.2
    created: "2021-11-09T13:33:38.4939306+01:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.x.x
    description: Keycloak is a high performance Java-based identity and access management solution. It lets developers add an authentication layer to their applications with minimum effort.
    digest: 4d850017c0a47089447b033acbf078eeb87875105c6620d93dd07a01ee479419
    home: https://www.keycloak.org
    icon: https://bitnami.com/assets/stacks/keycloak/img/keycloak-stack-220x234.png
    keywords:
    - keycloak
    - access-management
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: keycloak
    sources:
    - https://github.com/bitnami/bitnami-docker-keycloak
    - https://github.com/keycloak/keycloak
    urls:
    - charts/keycloak-5.1.6.tgz
    version: 5.1.6
  mariadb:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 10.5.12
    created: "2021-11-09T13:33:38.4979327+01:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: Fast, reliable, scalable, and easy to use open-source relational database system. MariaDB Server is intended for mission-critical, heavy-load production systems as well as for embedding into mass-deployed software. Highly available MariaDB cluster.
    digest: d479435b46c3a1a501eb868cdb0c848c26d2a40a911099e29e9565fa12fdc479
    home: https://github.com/bitnami/charts/tree/master/bitnami/mariadb
    icon: https://bitnami.com/assets/stacks/mariadb/img/mariadb-stack-220x234.png
    keywords:
    - mariadb
    - mysql
    - database
    - sql
    - prometheus
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: mariadb
    sources:
    - https://github.com/bitnami/bitnami-docker-mariadb
    - https://github.com/prometheus/mysqld_exporter
    - https://mariadb.org
    urls:
    - charts/mariadb-9.7.1.tgz
    version: 9.7.1
  postgresql:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 11.10.0
    created: "2021-11-09T13:33:38.5009323+01:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 1.x.x
    description: Chart for PostgreSQL, an object-relational database management system (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: eebe8f456cf98d5927a35666d1d899174dc4d3e09f26788033f761527bc90749
    home: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-110x117.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    - https://www.postgresql.org/
    urls:
    - charts/postgresql-10.1.1.tgz
    version: 10.1.1
  schulddossier:
  - annotations:
      artifacthub.io/containsSecurityUpdates: "true"
    apiVersion: v2
    appVersion: V1.0
    created: "2021-11-09T13:33:38.4869343+01:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.1.1
    - condition: mariadb.enabled
      name: mariadb
      repository: https://charts.bitnami.com/bitnami
      version: 9.7.1
    - condition: keycloak.enabled
      name: keycloak
      repository: https://charts.bitnami.com/bitnami
      version: 5.1.6
    digest: 15ead29b4aec8100ab6fad9e88d37ef9073b355c28979d56eef3089a5d41996f
    home: https://www.conduction.nl
    name: schulddossier
    urls:
    - schulddossier-1.0.0.tgz
    version: 1.0.0
generated: "2021-11-09T13:33:38.4709321+01:00"
